import { Product } from '@/types/shopify';

// Placeholder products for development before Shopify is connected
export const placeholderProducts: Product[] = [
  {
    id: 'gid://shopify/Product/1',
    handle: 'long-live-the-long-form-tee',
    title: 'Long Live the Long Form',
    description: 'Our manifesto tee. Cream organic cotton with forest green print. For those who believe reading is rebellion. Pre-shrunk and garment-dyed for that lived-in feel from day one.',
    descriptionHtml: '<p>Our manifesto tee. Cream organic cotton with forest green print. For those who believe reading is rebellion.</p><p>Pre-shrunk and garment-dyed for that lived-in feel from day one.</p>',
    featuredImage: {
      url: '/content/longliveflat.jpg',
      altText: 'Long Live the Long Form t-shirt',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/longliveflat.jpg',
        altText: 'Long Live the Long Form t-shirt flat lay',
        width: 800,
        height: 1000,
      },
      {
        url: '/content/longlive.jpg',
        altText: 'Long Live the Long Form t-shirt styled',
        width: 800,
        height: 1000,
      },
    ],
    price: '32.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/1',
        title: 'S',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'S' }],
      },
      {
        id: 'gid://shopify/ProductVariant/2',
        title: 'M',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'M' }],
      },
      {
        id: 'gid://shopify/ProductVariant/3',
        title: 'L',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'L' }],
      },
      {
        id: 'gid://shopify/ProductVariant/4',
        title: 'XL',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'XL' }],
      },
    ],
    options: [
      {
        id: 'gid://shopify/ProductOption/1',
        name: 'Size',
        values: ['S', 'M', 'L', 'XL'],
      },
    ],
    tags: ['tee', 't-shirt', 'apparel', 'manifesto'],
    productType: 'T-Shirts',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/2',
    handle: 'give-me-fiction-or-give-me-death-tee',
    title: 'Give Me Fiction or Give Me Death',
    description: 'The declaration tee. Black organic cotton with cream print. A statement for those who understand that fiction is not escape—it\'s the only way in.',
    descriptionHtml: '<p>The declaration tee. Black organic cotton with cream print.</p><p>A statement for those who understand that fiction is not escape—it\'s the only way in.</p>',
    featuredImage: {
      url: '/content/givemefiction.jpg',
      altText: 'Give Me Fiction or Give Me Death t-shirt',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/givemefiction.jpg',
        altText: 'Give Me Fiction or Give Me Death t-shirt',
        width: 800,
        height: 1000,
      },
      {
        url: '/content/fictionordeath.jpg',
        altText: 'Give Me Fiction or Give Me Death styled',
        width: 800,
        height: 1000,
      },
    ],
    price: '32.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/5',
        title: 'S',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'S' }],
      },
      {
        id: 'gid://shopify/ProductVariant/6',
        title: 'M',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'M' }],
      },
      {
        id: 'gid://shopify/ProductVariant/7',
        title: 'L',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'L' }],
      },
      {
        id: 'gid://shopify/ProductVariant/8',
        title: 'XL',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'XL' }],
      },
    ],
    options: [
      {
        id: 'gid://shopify/ProductOption/2',
        name: 'Size',
        values: ['S', 'M', 'L', 'XL'],
      },
    ],
    tags: ['tee', 't-shirt', 'apparel', 'declaration'],
    productType: 'T-Shirts',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/3',
    handle: 'read-slowly-or-die-trying-tee',
    title: 'Read Slowly or Die Trying',
    description: 'For the patient reader. Cream organic cotton with black print. Because attention is the rarest art, and you\'ve mastered it.',
    descriptionHtml: '<p>For the patient reader. Cream organic cotton with black print.</p><p>Because attention is the rarest art, and you\'ve mastered it.</p>',
    featuredImage: {
      url: '/content/readslow copy.jpg',
      altText: 'Read Slowly or Die Trying t-shirt',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/readslow copy.jpg',
        altText: 'Read Slowly or Die Trying t-shirt flat',
        width: 800,
        height: 1000,
      },
      {
        url: '/content/readslow.jpg',
        altText: 'Read Slowly or Die Trying styled',
        width: 800,
        height: 1000,
      },
    ],
    price: '32.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/9',
        title: 'S',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'S' }],
      },
      {
        id: 'gid://shopify/ProductVariant/10',
        title: 'M',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'M' }],
      },
      {
        id: 'gid://shopify/ProductVariant/11',
        title: 'L',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'L' }],
      },
      {
        id: 'gid://shopify/ProductVariant/12',
        title: 'XL',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'XL' }],
      },
    ],
    options: [
      {
        id: 'gid://shopify/ProductOption/3',
        name: 'Size',
        values: ['S', 'M', 'L', 'XL'],
      },
    ],
    tags: ['tee', 't-shirt', 'apparel'],
    productType: 'T-Shirts',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/4',
    handle: 'so-many-books-so-little-time-tee',
    title: 'So Many Books, So Little Time',
    description: 'The eternal lament. Natural organic cotton with black print. For those who understand that the TBR pile is not a problem—it\'s a lifestyle.',
    descriptionHtml: '<p>The eternal lament. Natural organic cotton with black print.</p><p>For those who understand that the TBR pile is not a problem—it\'s a lifestyle.</p>',
    featuredImage: {
      url: '/content/somanybooks copy.jpg',
      altText: 'So Many Books So Little Time t-shirt',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/somanybooks copy.jpg',
        altText: 'So Many Books So Little Time t-shirt flat',
        width: 800,
        height: 1000,
      },
      {
        url: '/content/somanybooks.jpg',
        altText: 'So Many Books So Little Time styled',
        width: 800,
        height: 1000,
      },
    ],
    price: '32.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/13',
        title: 'S',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'S' }],
      },
      {
        id: 'gid://shopify/ProductVariant/14',
        title: 'M',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'M' }],
      },
      {
        id: 'gid://shopify/ProductVariant/15',
        title: 'L',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'L' }],
      },
      {
        id: 'gid://shopify/ProductVariant/16',
        title: 'XL',
        availableForSale: true,
        price: '32.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'XL' }],
      },
    ],
    options: [
      {
        id: 'gid://shopify/ProductOption/4',
        name: 'Size',
        values: ['S', 'M', 'L', 'XL'],
      },
    ],
    tags: ['tee', 't-shirt', 'apparel'],
    productType: 'T-Shirts',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/5',
    handle: 'for-the-reader-who-stayed-bookmark',
    title: 'For The Reader Who Stayed',
    description: 'Our signature bookmark. Heavy cardstock with letterpress texture and gold foil detail. For those who turned every page.',
    descriptionHtml: '<p>Our signature bookmark. Heavy cardstock with letterpress texture and gold foil detail.</p><p>For those who turned every page.</p>',
    featuredImage: {
      url: '/content/withbleedAsset 52.png',
      altText: 'For The Reader Who Stayed bookmark',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/withbleedAsset 52.png',
        altText: 'For The Reader Who Stayed bookmark',
        width: 800,
        height: 1000,
      },
    ],
    price: '8.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/17',
        title: 'Default',
        availableForSale: true,
        price: '8.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Title', value: 'Default' }],
      },
    ],
    options: [],
    tags: ['bookmark', 'letterpress', 'literary'],
    productType: 'Bookmarks',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/6',
    handle: 'the-long-read-the-short-life-print',
    title: 'The Long Read, The Short Life',
    description: 'A typographic print that speaks to the melancholic devotion of every serious reader. Museum-quality archival paper. The perfect reminder of why we read.',
    descriptionHtml: '<p>A typographic print that speaks to the melancholic devotion of every serious reader.</p><p>Museum-quality archival paper. The perfect reminder of why we read.</p>',
    featuredImage: {
      url: '/content/withbleedAsset 72.png',
      altText: 'The Long Read The Short Life print',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/withbleedAsset 72.png',
        altText: 'The Long Read The Short Life print',
        width: 800,
        height: 1000,
      },
    ],
    price: '35.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/18',
        title: 'A4',
        availableForSale: true,
        price: '35.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'A4' }],
      },
      {
        id: 'gid://shopify/ProductVariant/19',
        title: 'A3',
        availableForSale: true,
        price: '55.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'A3' }],
      },
    ],
    options: [
      {
        id: 'gid://shopify/ProductOption/5',
        name: 'Size',
        values: ['A4', 'A3'],
      },
    ],
    tags: ['print', 'typography', 'literary'],
    productType: 'Prints',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/7',
    handle: 'pretension-earned-bookmark',
    title: 'Pretension, Earned',
    description: 'Brass bookmark with our motto engraved in a classic serif. Solid brass that develops a beautiful patina over time—like a well-read mind.',
    descriptionHtml: '<p>Brass bookmark with our motto engraved in a classic serif.</p><p>Solid brass that develops a beautiful patina over time—like a well-read mind.</p>',
    featuredImage: {
      url: '/content/withbleedAsset 82.png',
      altText: 'Pretension Earned brass bookmark',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/withbleedAsset 82.png',
        altText: 'Pretension Earned brass bookmark',
        width: 800,
        height: 1000,
      },
    ],
    price: '18.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/20',
        title: 'Default',
        availableForSale: true,
        price: '18.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Title', value: 'Default' }],
      },
    ],
    options: [],
    tags: ['bookmark', 'brass', 'literary'],
    productType: 'Bookmarks',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/8',
    handle: 'better-read-than-dead-print',
    title: 'Better Read Than Dead',
    description: 'Our tagline as art. Elegant serif typography on museum-quality archival paper. A declaration for your wall.',
    descriptionHtml: '<p>Our tagline as art. Elegant serif typography on museum-quality archival paper.</p><p>A declaration for your wall.</p>',
    featuredImage: {
      url: '/content/withbleedAsset 92.png',
      altText: 'Better Read Than Dead print',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/withbleedAsset 92.png',
        altText: 'Better Read Than Dead print',
        width: 800,
        height: 1000,
      },
    ],
    price: '35.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/21',
        title: 'A4',
        availableForSale: true,
        price: '35.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'A4' }],
      },
      {
        id: 'gid://shopify/ProductVariant/22',
        title: 'A3',
        availableForSale: true,
        price: '55.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Size', value: 'A3' }],
      },
    ],
    options: [
      {
        id: 'gid://shopify/ProductOption/6',
        name: 'Size',
        values: ['A4', 'A3'],
      },
    ],
    tags: ['print', 'typography', 'literary'],
    productType: 'Prints',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/9',
    handle: 'marginalia-bookmark',
    title: 'Marginalia',
    description: 'A bookmark celebrating the art of annotation. Cream cardstock with hand-drawn marginalia illustrations. For readers who talk back to their books.',
    descriptionHtml: '<p>A bookmark celebrating the art of annotation. Cream cardstock with hand-drawn marginalia illustrations.</p><p>For readers who talk back to their books.</p>',
    featuredImage: {
      url: '/content/Untitled-4.jpg',
      altText: 'Marginalia bookmark',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/Untitled-4.jpg',
        altText: 'Marginalia bookmark',
        width: 800,
        height: 1000,
      },
    ],
    price: '6.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/23',
        title: 'Default',
        availableForSale: true,
        price: '6.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Title', value: 'Default' }],
      },
    ],
    options: [],
    tags: ['bookmark', 'marginalia', 'literary'],
    productType: 'Bookmarks',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/10',
    handle: 'chapter-one-bookmark',
    title: 'Chapter One',
    description: 'Begin again. Minimalist design for the reader who loves fresh starts. Heavy cream cardstock with embossed detail.',
    descriptionHtml: '<p>Begin again. Minimalist design for the reader who loves fresh starts.</p><p>Heavy cream cardstock with embossed detail.</p>',
    featuredImage: {
      url: '/content/Untitled-5.jpg',
      altText: 'Chapter One bookmark',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/Untitled-5.jpg',
        altText: 'Chapter One bookmark',
        width: 800,
        height: 1000,
      },
    ],
    price: '6.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/24',
        title: 'Default',
        availableForSale: true,
        price: '6.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Title', value: 'Default' }],
      },
    ],
    options: [],
    tags: ['bookmark', 'minimal', 'literary'],
    productType: 'Bookmarks',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/11',
    handle: 'the-last-page-bookmark',
    title: 'The Last Page',
    description: 'For the reader who always finishes. Dark cardstock with gold foil lettering. A reminder that endings are beginnings.',
    descriptionHtml: '<p>For the reader who always finishes. Dark cardstock with gold foil lettering.</p><p>A reminder that endings are beginnings.</p>',
    featuredImage: {
      url: '/content/Untitled-7.jpg',
      altText: 'The Last Page bookmark',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/Untitled-7.jpg',
        altText: 'The Last Page bookmark',
        width: 800,
        height: 1000,
      },
    ],
    price: '6.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/25',
        title: 'Default',
        availableForSale: true,
        price: '6.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Title', value: 'Default' }],
      },
    ],
    options: [],
    tags: ['bookmark', 'elegant', 'literary'],
    productType: 'Bookmarks',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/12',
    handle: 'dog-eared-bookmark',
    title: 'Dog-Eared',
    description: 'A playful nod to the cardinal sin. Cream cardstock with a hand-drawn folded corner illustration. Use this instead.',
    descriptionHtml: '<p>A playful nod to the cardinal sin. Cream cardstock with a hand-drawn folded corner illustration.</p><p>Use this instead.</p>',
    featuredImage: {
      url: '/content/Untitled-8.jpg',
      altText: 'Dog-Eared bookmark',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/Untitled-8.jpg',
        altText: 'Dog-Eared bookmark',
        width: 800,
        height: 1000,
      },
    ],
    price: '6.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/26',
        title: 'Default',
        availableForSale: true,
        price: '6.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Title', value: 'Default' }],
      },
    ],
    options: [],
    tags: ['bookmark', 'playful', 'literary'],
    productType: 'Bookmarks',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/13',
    handle: 'tbr-pile-bookmark',
    title: 'TBR Pile',
    description: 'The eternal optimist\'s bookmark. Features a hand-illustrated stack of books. For readers whose ambitions exceed their shelves.',
    descriptionHtml: '<p>The eternal optimist\'s bookmark. Features a hand-illustrated stack of books.</p><p>For readers whose ambitions exceed their shelves.</p>',
    featuredImage: {
      url: '/content/Untitled-9.jpg',
      altText: 'TBR Pile bookmark',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/content/Untitled-9.jpg',
        altText: 'TBR Pile bookmark',
        width: 800,
        height: 1000,
      },
    ],
    price: '6.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/27',
        title: 'Default',
        availableForSale: true,
        price: '6.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Title', value: 'Default' }],
      },
    ],
    options: [],
    tags: ['bookmark', 'tbr', 'literary'],
    productType: 'Bookmarks',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/14',
    handle: 'the-readers-companion-anthology',
    title: 'The Reader\'s Companion',
    description: 'A curated anthology of essays on the art of reading. From Woolf to Borges, the voices that shaped how we think about literature.',
    descriptionHtml: '<p>A curated anthology of essays on the art of reading.</p><p>From Woolf to Borges, the voices that shaped how we think about literature.</p>',
    featuredImage: {
      url: '/images/41e893d89a5edab55a6cf30298981869.jpg',
      altText: 'The Reader\'s Companion anthology',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/images/41e893d89a5edab55a6cf30298981869.jpg',
        altText: 'The Reader\'s Companion anthology',
        width: 800,
        height: 1000,
      },
    ],
    price: '24.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/28',
        title: 'Hardcover',
        availableForSale: true,
        price: '24.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Format', value: 'Hardcover' }],
      },
      {
        id: 'gid://shopify/ProductVariant/29',
        title: 'Paperback',
        availableForSale: true,
        price: '16.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Format', value: 'Paperback' }],
      },
    ],
    options: [
      {
        id: 'gid://shopify/ProductOption/7',
        name: 'Format',
        values: ['Hardcover', 'Paperback'],
      },
    ],
    tags: ['book', 'anthology', 'literary'],
    productType: 'Books',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/15',
    handle: 'marginalia-journal',
    title: 'Marginalia Journal',
    description: 'A reading journal for the serious annotator. Archival paper, lay-flat binding, and prompts designed for deep literary engagement.',
    descriptionHtml: '<p>A reading journal for the serious annotator.</p><p>Archival paper, lay-flat binding, and prompts designed for deep literary engagement.</p>',
    featuredImage: {
      url: '/images/df66b392638924a895cd0c1c78ebdbb2.jpg',
      altText: 'Marginalia Journal',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/images/df66b392638924a895cd0c1c78ebdbb2.jpg',
        altText: 'Marginalia Journal',
        width: 800,
        height: 1000,
      },
    ],
    price: '28.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/30',
        title: 'Default',
        availableForSale: true,
        price: '28.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Title', value: 'Default' }],
      },
    ],
    options: [],
    tags: ['book', 'journal', 'literary'],
    productType: 'Books',
    availableForSale: true,
  },
  {
    id: 'gid://shopify/Product/16',
    handle: 'on-rereading-essays',
    title: 'On Rereading',
    description: 'Why we return to the books that made us. A collection of essays exploring the art of rereading and what it reveals about ourselves.',
    descriptionHtml: '<p>Why we return to the books that made us.</p><p>A collection of essays exploring the art of rereading and what it reveals about ourselves.</p>',
    featuredImage: {
      url: '/images/05224f277ba3667270902b448b936b64.jpg',
      altText: 'On Rereading essays collection',
      width: 800,
      height: 1000,
    },
    images: [
      {
        url: '/images/05224f277ba3667270902b448b936b64.jpg',
        altText: 'On Rereading essays collection',
        width: 800,
        height: 1000,
      },
    ],
    price: '22.00',
    compareAtPrice: null,
    currencyCode: 'GBP',
    variants: [
      {
        id: 'gid://shopify/ProductVariant/31',
        title: 'Default',
        availableForSale: true,
        price: '22.00',
        currencyCode: 'GBP',
        selectedOptions: [{ name: 'Title', value: 'Default' }],
      },
    ],
    options: [],
    tags: ['book', 'essays', 'literary'],
    productType: 'Books',
    availableForSale: true,
  },
];

// Category data
export const categories = [
  { handle: 'prints', title: 'Prints', description: 'Fine art prints for literary souls.' },
  { handle: 'bookmarks', title: 'Bookmarks', description: 'Mark your place with intention.' },
  { handle: 't-shirts', title: 'T-Shirts', description: 'Wear your reading on your sleeve.' },
  { handle: 'books', title: 'Books', description: 'Curated editions for the discerning reader.' },
];

// Helper to get products by category
export function getProductsByCategory(categoryHandle: string): Product[] {
  const categoryMap: Record<string, string> = {
    prints: 'Prints',
    bookmarks: 'Bookmarks',
    't-shirts': 'T-Shirts',
    books: 'Books',
  };

  const productType = categoryMap[categoryHandle];
  if (!productType) return placeholderProducts;

  return placeholderProducts.filter((p) => p.productType === productType);
}

// Helper to get product by handle
export function getProductByHandle(handle: string): Product | undefined {
  return placeholderProducts.find((p) => p.handle === handle);
}

// Helper to get featured products
export function getFeaturedProducts(count: number = 4): Product[] {
  return placeholderProducts.slice(0, count);
}

// Helper to get related products
export function getRelatedProducts(currentHandle: string, count: number = 3): Product[] {
  return placeholderProducts
    .filter((p) => p.handle !== currentHandle)
    .slice(0, count);
}
